/**
 * Maps ISO 3166-1 numeric codes (used by world-atlas TopoJSON) to country
 * metadata.  The `slugs` array lists plausible category-slug variants so we
 * can match DB categories to globe polygons.
 */

export type CountryEntry = {
  code: string;        // ISO 3166-1 numeric (string for TopoJSON compat)
  name: string;        // Display name
  slugs: string[];     // Category slugs that may match this country
};

export const COUNTRIES: CountryEntry[] = [
  { code: "004", name: "Afghanistan", slugs: ["afghanistan"] },
  { code: "008", name: "Albania", slugs: ["albania"] },
  { code: "012", name: "Algeria", slugs: ["algeria"] },
  { code: "020", name: "Andorra", slugs: ["andorra"] },
  { code: "024", name: "Angola", slugs: ["angola"] },
  { code: "028", name: "Antigua and Barbuda", slugs: ["antigua-and-barbuda", "antigua"] },
  { code: "032", name: "Argentina", slugs: ["argentina"] },
  { code: "051", name: "Armenia", slugs: ["armenia"] },
  { code: "036", name: "Australia", slugs: ["australia"] },
  { code: "040", name: "Austria", slugs: ["austria"] },
  { code: "031", name: "Azerbaijan", slugs: ["azerbaijan"] },
  { code: "044", name: "Bahamas", slugs: ["bahamas"] },
  { code: "048", name: "Bahrain", slugs: ["bahrain"] },
  { code: "050", name: "Bangladesh", slugs: ["bangladesh"] },
  { code: "052", name: "Barbados", slugs: ["barbados"] },
  { code: "112", name: "Belarus", slugs: ["belarus"] },
  { code: "056", name: "Belgium", slugs: ["belgium"] },
  { code: "084", name: "Belize", slugs: ["belize"] },
  { code: "204", name: "Benin", slugs: ["benin"] },
  { code: "064", name: "Bhutan", slugs: ["bhutan"] },
  { code: "068", name: "Bolivia", slugs: ["bolivia"] },
  { code: "070", name: "Bosnia and Herzegovina", slugs: ["bosnia-and-herzegovina", "bosnia"] },
  { code: "072", name: "Botswana", slugs: ["botswana"] },
  { code: "076", name: "Brazil", slugs: ["brazil"] },
  { code: "096", name: "Brunei", slugs: ["brunei"] },
  { code: "100", name: "Bulgaria", slugs: ["bulgaria"] },
  { code: "854", name: "Burkina Faso", slugs: ["burkina-faso"] },
  { code: "108", name: "Burundi", slugs: ["burundi"] },
  { code: "132", name: "Cabo Verde", slugs: ["cabo-verde", "cape-verde"] },
  { code: "116", name: "Cambodia", slugs: ["cambodia"] },
  { code: "120", name: "Cameroon", slugs: ["cameroon"] },
  { code: "124", name: "Canada", slugs: ["canada"] },
  { code: "140", name: "Central African Republic", slugs: ["central-african-republic"] },
  { code: "148", name: "Chad", slugs: ["chad"] },
  { code: "152", name: "Chile", slugs: ["chile"] },
  { code: "156", name: "China", slugs: ["china"] },
  { code: "170", name: "Colombia", slugs: ["colombia"] },
  { code: "174", name: "Comoros", slugs: ["comoros"] },
  { code: "178", name: "Congo", slugs: ["congo", "republic-of-the-congo"] },
  { code: "180", name: "DR Congo", slugs: ["dr-congo", "democratic-republic-of-the-congo"] },
  { code: "188", name: "Costa Rica", slugs: ["costa-rica"] },
  { code: "384", name: "Ivory Coast", slugs: ["ivory-coast", "cote-divoire"] },
  { code: "191", name: "Croatia", slugs: ["croatia"] },
  { code: "192", name: "Cuba", slugs: ["cuba"] },
  { code: "196", name: "Cyprus", slugs: ["cyprus"] },
  { code: "203", name: "Czech Republic", slugs: ["czech-republic", "czechia"] },
  { code: "208", name: "Denmark", slugs: ["denmark"] },
  { code: "262", name: "Djibouti", slugs: ["djibouti"] },
  { code: "212", name: "Dominica", slugs: ["dominica"] },
  { code: "214", name: "Dominican Republic", slugs: ["dominican-republic"] },
  { code: "218", name: "Ecuador", slugs: ["ecuador"] },
  { code: "818", name: "Egypt", slugs: ["egypt"] },
  { code: "222", name: "El Salvador", slugs: ["el-salvador"] },
  { code: "226", name: "Equatorial Guinea", slugs: ["equatorial-guinea"] },
  { code: "232", name: "Eritrea", slugs: ["eritrea"] },
  { code: "233", name: "Estonia", slugs: ["estonia"] },
  { code: "748", name: "Eswatini", slugs: ["eswatini", "swaziland"] },
  { code: "231", name: "Ethiopia", slugs: ["ethiopia"] },
  { code: "242", name: "Fiji", slugs: ["fiji"] },
  { code: "246", name: "Finland", slugs: ["finland"] },
  { code: "250", name: "France", slugs: ["france"] },
  { code: "266", name: "Gabon", slugs: ["gabon"] },
  { code: "270", name: "Gambia", slugs: ["gambia"] },
  { code: "268", name: "Georgia", slugs: ["georgia"] },
  { code: "276", name: "Germany", slugs: ["germany"] },
  { code: "288", name: "Ghana", slugs: ["ghana"] },
  { code: "300", name: "Greece", slugs: ["greece"] },
  { code: "308", name: "Grenada", slugs: ["grenada"] },
  { code: "320", name: "Guatemala", slugs: ["guatemala"] },
  { code: "324", name: "Guinea", slugs: ["guinea"] },
  { code: "624", name: "Guinea-Bissau", slugs: ["guinea-bissau"] },
  { code: "328", name: "Guyana", slugs: ["guyana"] },
  { code: "332", name: "Haiti", slugs: ["haiti"] },
  { code: "340", name: "Honduras", slugs: ["honduras"] },
  { code: "348", name: "Hungary", slugs: ["hungary"] },
  { code: "352", name: "Iceland", slugs: ["iceland"] },
  { code: "356", name: "India", slugs: ["india"] },
  { code: "360", name: "Indonesia", slugs: ["indonesia"] },
  { code: "364", name: "Iran", slugs: ["iran"] },
  { code: "368", name: "Iraq", slugs: ["iraq"] },
  { code: "372", name: "Ireland", slugs: ["ireland"] },
  { code: "376", name: "Israel", slugs: ["israel"] },
  { code: "380", name: "Italy", slugs: ["italy"] },
  { code: "388", name: "Jamaica", slugs: ["jamaica"] },
  { code: "392", name: "Japan", slugs: ["japan"] },
  { code: "400", name: "Jordan", slugs: ["jordan"] },
  { code: "398", name: "Kazakhstan", slugs: ["kazakhstan"] },
  { code: "404", name: "Kenya", slugs: ["kenya"] },
  { code: "296", name: "Kiribati", slugs: ["kiribati"] },
  { code: "408", name: "North Korea", slugs: ["north-korea"] },
  { code: "410", name: "South Korea", slugs: ["south-korea", "korea"] },
  { code: "414", name: "Kuwait", slugs: ["kuwait"] },
  { code: "417", name: "Kyrgyzstan", slugs: ["kyrgyzstan"] },
  { code: "418", name: "Laos", slugs: ["laos"] },
  { code: "428", name: "Latvia", slugs: ["latvia"] },
  { code: "422", name: "Lebanon", slugs: ["lebanon"] },
  { code: "426", name: "Lesotho", slugs: ["lesotho"] },
  { code: "430", name: "Liberia", slugs: ["liberia"] },
  { code: "434", name: "Libya", slugs: ["libya"] },
  { code: "438", name: "Liechtenstein", slugs: ["liechtenstein"] },
  { code: "440", name: "Lithuania", slugs: ["lithuania"] },
  { code: "442", name: "Luxembourg", slugs: ["luxembourg"] },
  { code: "450", name: "Madagascar", slugs: ["madagascar"] },
  { code: "454", name: "Malawi", slugs: ["malawi"] },
  { code: "458", name: "Malaysia", slugs: ["malaysia"] },
  { code: "462", name: "Maldives", slugs: ["maldives"] },
  { code: "466", name: "Mali", slugs: ["mali"] },
  { code: "470", name: "Malta", slugs: ["malta"] },
  { code: "584", name: "Marshall Islands", slugs: ["marshall-islands"] },
  { code: "478", name: "Mauritania", slugs: ["mauritania"] },
  { code: "480", name: "Mauritius", slugs: ["mauritius"] },
  { code: "484", name: "Mexico", slugs: ["mexico"] },
  { code: "583", name: "Micronesia", slugs: ["micronesia"] },
  { code: "498", name: "Moldova", slugs: ["moldova"] },
  { code: "492", name: "Monaco", slugs: ["monaco"] },
  { code: "496", name: "Mongolia", slugs: ["mongolia"] },
  { code: "499", name: "Montenegro", slugs: ["montenegro"] },
  { code: "504", name: "Morocco", slugs: ["morocco"] },
  { code: "508", name: "Mozambique", slugs: ["mozambique"] },
  { code: "104", name: "Myanmar", slugs: ["myanmar", "burma"] },
  { code: "516", name: "Namibia", slugs: ["namibia"] },
  { code: "520", name: "Nauru", slugs: ["nauru"] },
  { code: "524", name: "Nepal", slugs: ["nepal"] },
  { code: "528", name: "Netherlands", slugs: ["netherlands"] },
  { code: "554", name: "New Zealand", slugs: ["new-zealand"] },
  { code: "558", name: "Nicaragua", slugs: ["nicaragua"] },
  { code: "562", name: "Niger", slugs: ["niger"] },
  { code: "566", name: "Nigeria", slugs: ["nigeria"] },
  { code: "807", name: "North Macedonia", slugs: ["north-macedonia", "macedonia"] },
  { code: "578", name: "Norway", slugs: ["norway"] },
  { code: "512", name: "Oman", slugs: ["oman"] },
  { code: "586", name: "Pakistan", slugs: ["pakistan"] },
  { code: "585", name: "Palau", slugs: ["palau"] },
  { code: "275", name: "Palestine", slugs: ["palestine"] },
  { code: "591", name: "Panama", slugs: ["panama"] },
  { code: "598", name: "Papua New Guinea", slugs: ["papua-new-guinea"] },
  { code: "600", name: "Paraguay", slugs: ["paraguay"] },
  { code: "604", name: "Peru", slugs: ["peru"] },
  { code: "608", name: "Philippines", slugs: ["philippines"] },
  { code: "616", name: "Poland", slugs: ["poland"] },
  { code: "620", name: "Portugal", slugs: ["portugal"] },
  { code: "634", name: "Qatar", slugs: ["qatar"] },
  { code: "642", name: "Romania", slugs: ["romania"] },
  { code: "643", name: "Russia", slugs: ["russia"] },
  { code: "646", name: "Rwanda", slugs: ["rwanda"] },
  { code: "659", name: "Saint Kitts and Nevis", slugs: ["saint-kitts-and-nevis"] },
  { code: "662", name: "Saint Lucia", slugs: ["saint-lucia"] },
  { code: "670", name: "Saint Vincent and the Grenadines", slugs: ["saint-vincent-and-the-grenadines"] },
  { code: "882", name: "Samoa", slugs: ["samoa"] },
  { code: "674", name: "San Marino", slugs: ["san-marino"] },
  { code: "678", name: "Sao Tome and Principe", slugs: ["sao-tome-and-principe"] },
  { code: "682", name: "Saudi Arabia", slugs: ["saudi-arabia"] },
  { code: "686", name: "Senegal", slugs: ["senegal"] },
  { code: "688", name: "Serbia", slugs: ["serbia"] },
  { code: "690", name: "Seychelles", slugs: ["seychelles"] },
  { code: "694", name: "Sierra Leone", slugs: ["sierra-leone"] },
  { code: "702", name: "Singapore", slugs: ["singapore"] },
  { code: "703", name: "Slovakia", slugs: ["slovakia"] },
  { code: "705", name: "Slovenia", slugs: ["slovenia"] },
  { code: "090", name: "Solomon Islands", slugs: ["solomon-islands"] },
  { code: "706", name: "Somalia", slugs: ["somalia"] },
  { code: "710", name: "South Africa", slugs: ["south-africa"] },
  { code: "728", name: "South Sudan", slugs: ["south-sudan"] },
  { code: "724", name: "Spain", slugs: ["spain"] },
  { code: "144", name: "Sri Lanka", slugs: ["sri-lanka"] },
  { code: "729", name: "Sudan", slugs: ["sudan"] },
  { code: "740", name: "Suriname", slugs: ["suriname"] },
  { code: "752", name: "Sweden", slugs: ["sweden"] },
  { code: "756", name: "Switzerland", slugs: ["switzerland"] },
  { code: "760", name: "Syria", slugs: ["syria"] },
  { code: "158", name: "Taiwan", slugs: ["taiwan"] },
  { code: "762", name: "Tajikistan", slugs: ["tajikistan"] },
  { code: "834", name: "Tanzania", slugs: ["tanzania"] },
  { code: "764", name: "Thailand", slugs: ["thailand"] },
  { code: "626", name: "Timor-Leste", slugs: ["timor-leste", "east-timor"] },
  { code: "768", name: "Togo", slugs: ["togo"] },
  { code: "776", name: "Tonga", slugs: ["tonga"] },
  { code: "780", name: "Trinidad and Tobago", slugs: ["trinidad-and-tobago"] },
  { code: "788", name: "Tunisia", slugs: ["tunisia"] },
  { code: "792", name: "Turkey", slugs: ["turkey", "turkiye"] },
  { code: "795", name: "Turkmenistan", slugs: ["turkmenistan"] },
  { code: "798", name: "Tuvalu", slugs: ["tuvalu"] },
  { code: "800", name: "Uganda", slugs: ["uganda"] },
  { code: "804", name: "Ukraine", slugs: ["ukraine"] },
  { code: "784", name: "United Arab Emirates", slugs: ["united-arab-emirates", "uae"] },
  { code: "826", name: "United Kingdom", slugs: ["united-kingdom", "uk"] },
  { code: "840", name: "United States", slugs: ["united-states", "usa", "us"] },
  { code: "858", name: "Uruguay", slugs: ["uruguay"] },
  { code: "860", name: "Uzbekistan", slugs: ["uzbekistan"] },
  { code: "548", name: "Vanuatu", slugs: ["vanuatu"] },
  { code: "336", name: "Vatican City", slugs: ["vatican-city", "holy-see"] },
  { code: "862", name: "Venezuela", slugs: ["venezuela"] },
  { code: "704", name: "Vietnam", slugs: ["vietnam"] },
  { code: "887", name: "Yemen", slugs: ["yemen"] },
  { code: "894", name: "Zambia", slugs: ["zambia"] },
  { code: "716", name: "Zimbabwe", slugs: ["zimbabwe"] },
];

/** Lookup: numeric code -> country entry */
export const CODE_TO_COUNTRY = new Map(COUNTRIES.map((c) => [c.code, c]));

/** Lookup: any slug variant -> country entry */
export const SLUG_TO_COUNTRY = new Map(
  COUNTRIES.flatMap((c) => c.slugs.map((s) => [s, c])),
);

/** Lookup: lowercase country name -> country entry */
export const NAME_TO_COUNTRY = new Map(
  COUNTRIES.map((c) => [c.name.toLowerCase(), c]),
);
